"use client";
import {useEffect,useState} from 'react';
import {apiKeySettingsUrl,integrationCredentialsReady,integrationRequest,integrationTiles,type Integration,type IntegrationKind} from '../lib/homepage-integrations';
import {BookmarkGroups} from './bookmark-groups';
import type {Bookmark} from '../lib/linkwarden';
const blank={type:'seerr',name:'Seerr',group:'Media',url:'',appUrl:'',authMode:'apiKey',apiKey:'',username:'',password:'',showApp:true,linkId:null as number|null};
type Props={csrfToken:string;isAdmin:boolean;initialType?:string;onFinish?:()=>void;editorOnly?:boolean;initialValues?:{name:string;url:string;collection:string};links?:Bookmark[];onItemsChange?:(items:Integration[])=>void};
export function HomepageIntegrations({csrfToken,isAdmin,initialType,onFinish,editorOnly=false,initialValues,links=[],onItemsChange}:Props) {
  const [items,setItems]=useState<Integration[]>([]),[catalog,setCatalog]=useState<IntegrationKind[]>([]);
  const [form,setForm]=useState(blank),[editing,setEditing]=useState<number|null>(null),[open,setOpen]=useState(false);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  const [credentialChoice,setCredentialChoice]=useState(false);
  const [visible,setVisible]=useState(false),[query,setQuery]=useState(''),[appMode,setAppMode]=useState<'new'|'existing'>('new');
  useEffect(()=>{let cancelled=false;Promise.all([integrationRequest<{integrations:Integration[]}>('',csrfToken),integrationRequest<{integrations:IntegrationKind[]}>('/catalog',csrfToken)]).then(([result,kinds])=>{if(!cancelled){setItems(result.integrations);setCatalog(kinds.integrations);setLoaded(true);}}).catch(failure=>{if(!cancelled)setError(failure.message);});return()=>{cancelled=true;};},[csrfToken]);
  useEffect(()=>{if(loaded)onItemsChange?.(items);},[items,loaded,onItemsChange]);
  useEffect(()=>{if(initialType){setForm({...blank,type:initialType,name:initialValues?.name||initialType,group:initialValues?.collection||'Media',url:initialValues?.url||'',authMode:initialType==='jellyfin'?'password':'apiKey'});setOpen(true);}},[initialType]);
  const kind=catalog.find(item=>item.type===form.type);
  const keyLink=apiKeySettingsUrl(form.type,form.url);
  const close=()=>{setOpen(false);setForm(blank);setVisible(false);setAppMode('new');setCredentialChoice(false);onFinish?.();};
  async function refresh(item:Integration) {setBusy(true);setError('');try{const value=await integrationRequest<{summary:Integration['summary']}>(`/${item.id}/status`,csrfToken);setItems(items=>items.map(old=>old.id===item.id?{...old,summary:value.summary}:old));}catch(failure){setError(failure instanceof Error?failure.message:'Verbinding mislukt.');}finally{setBusy(false);}}
  return <section className="homepage-integrations" aria-label="Homepage-integraties">{!editorOnly&&<div className="bookmark-section-heading"><div><h4>Integraties</h4><p>Verbind je toepassingen voor informatie op Homepage en toekomstige widgets.</p></div>{isAdmin&&<button onClick={()=>{setForm(blank);setEditing(null);setAppMode('new');setVisible(false);setOpen(!open);setError('');}}>Integratie toevoegen</button>}</div>}
    {error&&<p className="config-error" role="alert">{error}</p>}
    {credentialChoice&&<div className="bookmark-form" role="alertdialog" aria-label="Toegangsgegevens toevoegen"><p>Wil je een account of API-sleutel toevoegen?</p><p>Zonder toegangsgegevens bewaren we alleen een gewone Homepage-link.</p><div className="form-actions"><button autoFocus disabled={busy} onClick={()=>setCredentialChoice(false)}>Ja, gegevens invullen</button><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{if(!(form.showApp&&appMode==='existing'&&form.linkId)){const response=await fetch('/api/homepage/links',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrfToken},body:JSON.stringify({name:form.name,url:form.appUrl||form.url,collection:form.group,description:'',icon:form.type==='seerr'?'jellyseerr':form.type})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Link kon niet worden opgeslagen.');}close();}catch(failure){setError(failure instanceof Error?failure.message:'Opslaan mislukt.');}finally{setBusy(false);}}}>Nee, alleen link opslaan</button></div></div>}
    {open&&isAdmin&&<form className="bookmark-form integration-editor" onSubmit={async event=>{event.preventDefault();if(!integrationCredentialsReady(form)){if(editing){setError('Vul de toegangsgegevens opnieuw in om de koppeling te wijzigen.');}else{setCredentialChoice(true);}return;}setBusy(true);setError('');try{const value=await integrationRequest<{integration:Integration}>(editing?`/${editing}`:'',csrfToken,editing?'PUT':'POST',{...form,linkId:form.showApp&&appMode==='existing'?form.linkId:null});setItems(items=>editing?items.map(item=>item.id===editing?value.integration:item):[...items,value.integration]);close();}catch(failure){setError(failure instanceof Error?failure.message:'Verbinding mislukt.');}finally{setBusy(false);}}}>
      <div className="integration-editor-heading"><h3>{editing?'Integratie aanpassen':'Nieuwe integratie'}</h3><button type="button" disabled={busy} onClick={close} aria-label="Integratie sluiten">×</button></div>
      <fieldset disabled={busy} className="integration-fields"><label>Toepassing<select aria-label="Toepassing" disabled={editing!==null} value={form.type} onChange={event=>{const selected=catalog.find(item=>item.type===event.target.value)!;setForm({...blank,type:selected.type,name:selected.name,authMode:selected.type==='jellyfin'?'password':selected.authModes[0]});setAppMode('new');setVisible(false);}}>{catalog.map(item=><option key={item.type} value={item.type}>{item.name}</option>)}</select></label>
      <label>Naam *<input aria-label="Naam" required maxLength={300} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>URL *<input aria-label="URL" type="url" required maxLength={2048} placeholder="http://w.jellyfin.home/" value={form.url} onChange={event=>setForm({...form,url:event.target.value})}/></label>
      <fieldset><legend>Geheimen</legend><div className="integration-segments" role="group" aria-label="Aanmeldmethode">{kind?.authModes.map(mode=><button type="button" key={mode} aria-pressed={form.authMode===mode} onClick={()=>{setForm({...form,authMode:mode,apiKey:'',username:'',password:''});setVisible(false);}}>{mode==='apiKey'?'API-sleutel':'Gebruikersnaam & Wachtwoord'}</button>)}</div>
      {form.authMode==='password'&&<label>Gebruikersnaam *<input aria-label="Gebruikersnaam" autoComplete="off" maxLength={4096} value={form.username} onChange={event=>setForm({...form,username:event.target.value})}/></label>}
      <label>{form.authMode==='apiKey'?'API-sleutel *':'Wachtwoord *'}<small>Dit geheim kan niet worden opgehaald na aanmaken.</small><div className="integration-secret"><input aria-label={form.authMode==='apiKey'?'API-sleutel':'Wachtwoord'} autoComplete="new-password" type={visible?'text':'password'} maxLength={4096} value={form.authMode==='apiKey'?form.apiKey:form.password} onChange={event=>setForm({...form,[form.authMode==='apiKey'?'apiKey':'password']:event.target.value})}/><button type="button" aria-label={visible?'Geheim verbergen':'Geheim tonen'} aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?'◉':'◎'}</button></div></label>
      {keyLink?<a className="integration-key-link" href={keyLink} target="_blank" rel="noopener noreferrer">API-sleutel ophalen ↗</a>:<p className="bookmark-hint">Vul eerst de URL in om de pagina voor API-sleutels te openen.</p>}
      <p className="bookmark-hint">Versleuteld opgeslagen. Bij aanpassen vul je de toegangsgegevens opnieuw in.</p></fieldset>
      <label className="integration-checkbox"><input type="checkbox" checked={form.showApp} onChange={event=>setForm({...form,showApp:event.target.checked,linkId:null})}/> App aanmaken of koppelen</label><p className="bookmark-hint">Maak een Homepage-tegel met dezelfde naam en icoon, of koppel de integratie aan een bestaande link.</p>
      {form.showApp&&<fieldset><legend>Gekoppelde app</legend><div className="integration-segments" role="group" aria-label="App koppelen"><button type="button" aria-pressed={appMode==='new'} onClick={()=>{setAppMode('new');setForm({...form,linkId:null});}}>Nieuw</button><button type="button" aria-pressed={appMode==='existing'} onClick={()=>{setAppMode('existing');setForm({...form,linkId:null});}}>Bestaand</button></div>
        {appMode==='existing'?<label>Bestaande Homepage-link *<select aria-label="Bestaande Homepage-link" required value={form.linkId??''} onChange={event=>setForm({...form,linkId:Number(event.target.value)||null})}><option value="">Kies een link</option>{links.filter(link=>!items.some(item=>item.linkId===link.id&&item.id!==editing)).map(link=><option key={link.id} value={link.id}>{link.name} · {link.collection}</option>)}</select></label>:<><label>Groep *<input aria-label="Groep" required maxLength={200} value={form.group} onChange={event=>setForm({...form,group:event.target.value})}/></label><label>App URL<small>De URL die opent vanaf Homepage. Leeg: gebruik de integratie-URL.</small><input aria-label="App URL" type="url" maxLength={2048} placeholder="Aangepaste app-URL (optioneel)" value={form.appUrl} onChange={event=>setForm({...form,appUrl:event.target.value})}/></label></>}
      </fieldset>}</fieldset><p className="bookmark-hint">De aantallen worden gedeeld met gebruikers met Bookmarks-rechten. De geopende site gebruikt haar eigen login of SSO.</p>
      <div className="form-actions"><button type="button" disabled={busy} onClick={close}>Terug naar overzicht</button><button className="integration-submit" disabled={busy||!loaded} type="submit">{busy?'Verbinding controleren…':editing?'Verbinding testen en opslaan':'Verbinding testen en aanmaken'}</button></div>
    </form>}
    {!editorOnly&&loaded&&items.length>0&&<><label className="homepage-search">Integraties zoeken<input type="search" maxLength={200} value={query} onChange={event=>setQuery(event.target.value)}/></label><BookmarkGroups links={integrationTiles(items.filter(item=>`${item.name} ${item.group}`.toLowerCase().includes(query.toLowerCase())))}/><ul className="integration-controls">{items.map(item=><li key={item.id}><strong>{item.name}</strong><button disabled={busy} onClick={()=>void refresh(item)}>Aantallen vernieuwen</button>{isAdmin&&<><button disabled={busy} onClick={()=>{setForm({...blank,...item,linkId:item.linkId??null,apiKey:'',username:'',password:''});setAppMode(item.linkId?'existing':'new');setEditing(item.id);setOpen(true);setVisible(false);}}>Koppeling aanpassen</button><button disabled={busy} onClick={async()=>{if(!window.confirm(`Koppeling ${item.name} verwijderen?`))return;setBusy(true);setError('');try{await integrationRequest(`/${item.id}`,csrfToken,'DELETE');setItems(items=>items.filter(old=>old.id!==item.id));}catch(failure){setError(failure instanceof Error?failure.message:'Verwijderen mislukt.');}finally{setBusy(false);}}}>Koppeling verwijderen</button></>}</li>)}</ul><p className="bookmark-hint">Aantallen zijn van de laatste controle. Vernieuw ze voor de actuele stand.</p></>}
    {!editorOnly&&loaded&&items.length===0&&<p>Nog geen integraties gekoppeld.{isAdmin?' Voeg Seerr of Jellyfin toe.':''}</p>}
  </section>;
}
