"use client";
import {useEffect,useState} from 'react';
import {integrationRequest,integrationTiles,type Integration,type IntegrationKind} from '../lib/homepage-integrations';
import {BookmarkGroups} from './bookmark-groups';
const blank={type:'seerr',name:'Seerr',group:'Media',url:'',appUrl:'',authMode:'apiKey',apiKey:'',username:'',password:'',showApp:true};
export function HomepageIntegrations({csrfToken,isAdmin,initialType,onFinish,editorOnly=false,initialValues}:{csrfToken:string;isAdmin:boolean;initialType?:string;onFinish?:()=>void;editorOnly?:boolean;initialValues?:{name:string;url:string;collection:string}}) {
  const [items,setItems]=useState<Integration[]>([]),[catalog,setCatalog]=useState<IntegrationKind[]>([]);
  const [form,setForm]=useState(blank),[editing,setEditing]=useState<number|null>(null),[open,setOpen]=useState(false);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  const [visible,setVisible]=useState(false),[query,setQuery]=useState('');
  useEffect(()=>{let cancelled=false;Promise.all([integrationRequest<{integrations:Integration[]}>('',csrfToken),integrationRequest<{integrations:IntegrationKind[]}>('/catalog',csrfToken)]).then(([result,kinds])=>{if(!cancelled){setItems(result.integrations);setCatalog(kinds.integrations);setLoaded(true);}}).catch(failure=>{if(!cancelled)setError(failure.message);});return()=>{cancelled=true;};},[csrfToken]);
  useEffect(()=>{if(initialType){setForm({...blank,type:initialType,name:initialValues?.name||initialType,group:initialValues?.collection||'Media',url:initialValues?.url||'',appUrl:initialValues?.url||''});setOpen(true);}},[initialType]);
  const kind=catalog.find(item=>item.type===form.type);
  async function refresh(item:Integration) {setBusy(true);setError('');try{const value=await integrationRequest<{summary:Integration['summary']}>(`/${item.id}/status`,csrfToken);setItems(items=>items.map(old=>old.id===item.id?{...old,summary:value.summary}:old));}catch(failure){setError(failure instanceof Error?failure.message:'Verbinding mislukt.');}finally{setBusy(false);}}
  return <section className="homepage-integrations" aria-labelledby="integration-heading">{!editorOnly&&<div className="bookmark-section-heading"><div><h4 id="integration-heading">Integraties</h4><p>Verbind je toepassingen voor informatie op Homepage, Media en toekomstige widgets.</p></div>{isAdmin&&<button onClick={()=>{setForm(blank);setEditing(null);setVisible(false);setOpen(!open);setError('');}}>Integratie toevoegen</button>}</div>}
    {error&&<p className="config-error" role="alert">{error}</p>}
    {open&&isAdmin&&<form className="bookmark-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{const value=await integrationRequest<{integration:Integration}>(editing?`/${editing}`:'',csrfToken,editing?'PUT':'POST',form);setItems(items=>editing?items.map(item=>item.id===editing?value.integration:item):[...items,value.integration]);setForm(blank);setOpen(false);setVisible(false);onFinish?.();}catch(failure){setError(failure instanceof Error?failure.message:'Verbinding mislukt.');}finally{setBusy(false);}}}><h4>{editing?'Integratie aanpassen':'Nieuwe integratie'}</h4><label>Toepassing<select disabled={editing!==null} value={form.type} onChange={event=>{const selected=catalog.find(item=>item.type===event.target.value)!;setForm({...blank,type:selected.type,name:selected.name,authMode:selected.authModes[0]});setVisible(false);}}>{catalog.map(item=><option key={item.type} value={item.type}>{item.name}</option>)}</select></label>
      <label>Naam<input required maxLength={300} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Groep<input required maxLength={200} value={form.group} onChange={event=>setForm({...form,group:event.target.value})}/></label><label>API-adres<input type="url" required maxLength={2048} placeholder="https://jellyfin.example.nl" value={form.url} onChange={event=>setForm({...form,url:event.target.value})}/></label>
      <fieldset><legend>Toegangsgegevens</legend><label>Aanmeldmethode<select value={form.authMode} onChange={event=>{setForm({...form,authMode:event.target.value,apiKey:'',username:'',password:''});setVisible(false);}}>{kind?.authModes.map(mode=><option key={mode} value={mode}>{mode==='apiKey'?'API-sleutel':'Gebruikersnaam en wachtwoord'}</option>)}</select></label>
      {form.authMode==='password'&&<label>Gebruikersnaam<input required autoComplete="off" maxLength={4096} value={form.username} onChange={event=>setForm({...form,username:event.target.value})}/></label>}
      <label>{form.authMode==='apiKey'?'API-sleutel':'Wachtwoord'}<input required autoComplete="new-password" type={visible?'text':'password'} maxLength={4096} value={form.authMode==='apiKey'?form.apiKey:form.password} onChange={event=>setForm({...form,[form.authMode==='apiKey'?'apiKey':'password']:event.target.value})}/></label><button type="button" aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?'Geheim verbergen':'Geheim tonen'}</button><p>Versleuteld opgeslagen. Bij aanpassen vul je de toegangsgegevens opnieuw in. De aantallen zijn gedeeld met gebruikers die toegang tot Bookmarks hebben.</p></fieldset>
      <label><input type="checkbox" checked={form.showApp} onChange={event=>setForm({...form,showApp:event.target.checked})}/> Homepage-tegel tonen</label><label>Openingsadres (optioneel)<input type="url" maxLength={2048} placeholder="Leeg: gebruik het API-adres" value={form.appUrl} onChange={event=>setForm({...form,appUrl:event.target.value})}/></label><p>Deze koppeling meldt de toepassing aan voor API-gegevens. Inloggen in de geopende site volgt de eigen login of SSO van die toepassing.</p><div className="form-actions"><button disabled={busy}>{busy?'Verbinding controleren…':'Verbinding testen en opslaan'}</button><button type="button" disabled={busy} onClick={()=>{setOpen(false);setForm(blank);onFinish?.();}}>Annuleren</button></div></form>}
    {!editorOnly&&loaded&&items.length>0&&<><label className="homepage-search">Integraties zoeken<input type="search" maxLength={200} value={query} onChange={event=>setQuery(event.target.value)}/></label><BookmarkGroups links={integrationTiles(items.filter(item=>`${item.name} ${item.group}`.toLowerCase().includes(query.toLowerCase())))}/><ul className="integration-controls">{items.map(item=><li key={item.id}><strong>{item.name}</strong><button disabled={busy} onClick={()=>void refresh(item)}>Aantallen vernieuwen</button>{isAdmin&&<><button disabled={busy} onClick={()=>{setForm({...blank,...item,apiKey:'',username:'',password:''});setEditing(item.id);setOpen(true);setVisible(false);}}>Koppeling aanpassen</button><button disabled={busy} onClick={async()=>{if(!window.confirm(`Koppeling ${item.name} verwijderen?`))return;setBusy(true);setError('');try{await integrationRequest(`/${item.id}`,csrfToken,'DELETE');setItems(items=>items.filter(old=>old.id!==item.id));}catch(failure){setError(failure instanceof Error?failure.message:'Verwijderen mislukt.');}finally{setBusy(false);}}}>Koppeling verwijderen</button></>}</li>)}</ul><p className="bookmark-hint">Aantallen zijn van de laatste verbindingscontrole. Vernieuw ze voor de actuele stand.</p></>}
    {!editorOnly&&loaded&&items.length===0&&<p>Nog geen integraties gekoppeld.{isAdmin?' Voeg Seerr of Jellyfin toe.':''}</p>}
  </section>;
}
